### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by jstrugnell** [emp/custom-delve#1]
Hi, I've tried this on a trial Office 365 tenant and it's not working for me? Are you able to validate that it still works for you? I'm getting JavaScript errors that I'm overcoming one by one but it would be good if you could verify whether it should still just work as-is?

Thanks.

**Comment by emp** [comment]
I'm creating a trial to set it up again since my old one is gone.

**Comment by emp** [comment]
I've just found a new 3rd pre-script added to the page, the big profile name not showing is not working even in the default one for me, hope that helps!
